// @generated by js/codegen/generate.ts — DO NOT EDIT.
// Run `npm run codegen` after editing js/codegen/schema.ts.

import Foundation

public enum JSONValue: Codable, Equatable, Sendable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case array([JSONValue])
    case object([String: JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let bool = try? container.decode(Bool.self) {
            self = .bool(bool)
        } else if let number = try? container.decode(Double.self) {
            self = .number(number)
        } else if let string = try? container.decode(String.self) {
            self = .string(string)
        } else if let array = try? container.decode([JSONValue].self) {
            self = .array(array)
        } else if let object = try? container.decode([String: JSONValue].self) {
            self = .object(object)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container, debugDescription: "Unsupported JSON value")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}

public struct RNNode: Codable, Equatable, Identifiable, Sendable {
    public let id: Int
    public let type: String
    public let props: [String: JSONValue]
    public let children: [RNNode]

    public func string(_ key: String) -> String? {
        if case .string(let value)? = props[key] { return value }
        return nil
    }

    public func double(_ key: String) -> Double? {
        if case .number(let value)? = props[key] { return value }
        return nil
    }

    public func bool(_ key: String) -> Bool? {
        if case .bool(let value)? = props[key] { return value }
        return nil
    }

    public func stringArray(_ key: String) -> [String]? {
        guard case .array(let values)? = props[key] else { return nil }
        return values.compactMap {
            if case .string(let value) = $0 { return value }
            return nil
        }
    }
}

public struct RNTree: Codable, Equatable, Sendable {
    public let v: Int
    public let seq: Int
    public let root: RNNode?
}

public struct PublishedRelevance: Codable, Equatable, Sendable {
    public let score: Double
    public let durationMs: Double?
}

public struct PublishedControl: Codable, Equatable, Sendable {
    public let intent: String
    public let label: String
    public let systemName: String?
    /// ControlWidgetButton's second label, shown while the action runs
    public let actionLabel: String?
    /// ControlWidgetToggle's isOn; presence marks the control a toggle
    public let value: Bool?
}

public struct PublishedEntry: Codable, Equatable, Sendable {
    /// ms since epoch
    public let date: Double
    public let tree: RNNode?
    public let url: String?
    public let relevance: PublishedRelevance?

    public var entryDate: Date { Date(timeIntervalSince1970: date / 1000) }
}

public struct PublishedRelevantContext: Codable, Equatable, Sendable {
    /// the clue family; every other field belongs to exactly one kind
    public let kind: String
    public let date: Double?
    public let from: Double?
    public let to: Double?
    /// RelevanceKit DateKind — watchOS 26.0, dropped below it
    public let dateKind: String?
    public let latitude: Double?
    public let longitude: Double?
    public let radius: Double?
    /// MKPointOfInterestCategory member NAME — watchOS 26.0
    public let category: String?
    public let place: String?
    /// fitness | sleep | headphones condition case name
    public let condition: String?
}

public struct PublishedFamilyTimeline: Codable, Equatable, Sendable {
    public let entries: [PublishedEntry]
    public let reloadAfter: Double?
    public let relevantContexts: [PublishedRelevantContext]?

    public var reloadAfterDate: Date? {
        reloadAfter.map { Date(timeIntervalSince1970: $0 / 1000) }
    }
}

public struct PublishedWidgets: Codable, Equatable, Sendable {
    public let v: Int
    public let publishedAt: Double
    public let stateRevision: Int
    public let releaseId: String?
    public let widgets: [String: [String: PublishedFamilyTimeline]]
    public let controls: [String: PublishedControl]?
}

public enum RNWire {
    public static let version = 1
    public static let bridgeProtocol = 1
}

/// The capability features each native target provides (ARCH-01). A bundle
/// runs only if its required features are a subset (see CapabilityGate).
public enum HostFeatures {
    public static let watch: Set<String> = [
        "ai", "audio", "background", "bluetooth", "calendar", "connectivity", "core", "device",
        "haptics", "health", "iap", "keychain", "location", "network", "notifications", "ota",
        "push", "runtime", "sensors", "speech", "storage", "widgets", "workoutPlans", "workouts",
    ]
    public static let widget: Set<String> = ["core", "storage", "widgets"]
}

/// Feature id for each invoke-routed host method (ARCH-07). The host checks
/// it BEFORE dispatching an invoke, so a feature the consumer's HostPolicy
/// didn't authorize rejects typed (POLICY_DENIED) instead of reaching a
/// handler.
public enum HostInvokeFeatures {
    public static let byMethod: [String: String] = [
        "aiAvailability": "ai",
        "bleConnect": "bluetooth",
        "bleSubscribe": "bluetooth",
        "bleWrite": "bluetooth",
        "cancelFileTransfer": "connectivity",
        "currentEntitlements": "iap",
        "deleteReceivedFile": "connectivity",
        "enableWaterLock": "device",
        "endWorkout": "workouts",
        "getCalendarEvents": "calendar",
        "getConnectivityState": "connectivity",
        "getCurrentLocation": "location",
        "getDeviceInfo": "device",
        "getProducts": "iap",
        "getReminders": "calendar",
        "getUpdateState": "ota",
        "getWorkoutState": "workouts",
        "keychainDelete": "keychain",
        "keychainGet": "keychain",
        "keychainSet": "keychain",
        "listScheduledWorkoutPlans": "workoutPlans",
        "markUpdateHealthy": "ota",
        "openWorkoutPlanInWorkoutApp": "workoutPlans",
        "outstandingFileTransfers": "connectivity",
        "pauseWorkout": "workouts",
        "playAudio": "audio",
        "purchase": "iap",
        "queryActivitySummaries": "health",
        "queryHealthDailyStatistics": "health",
        "queryHealthHourlyStatistics": "health",
        "queryHealthSamples": "health",
        "queryHealthStatistics": "health",
        "queryPedometer": "sensors",
        "querySleepSamples": "health",
        "queryWorkoutHistory": "health",
        "readReceivedFile": "connectivity",
        "registerForRemoteNotifications": "push",
        "removeAllScheduledWorkoutPlans": "workoutPlans",
        "removeScheduledWorkoutPlan": "workoutPlans",
        "requestCalendarAccess": "calendar",
        "requestHealthAuthorization": "health",
        "requestNotificationPermission": "notifications",
        "requestWorkoutPlanAuthorization": "workoutPlans",
        "restorePurchases": "iap",
        "resumeWorkout": "workouts",
        "saveUpdate": "ota",
        "scheduleBackgroundRefresh": "background",
        "scheduleNotification": "notifications",
        "scheduleWorkoutPlan": "workoutPlans",
        "searchPOI": "location",
        "sendToPhone": "connectivity",
        "speak": "speech",
        "startExtendedRuntimeSession": "runtime",
        "startHealthUpdates": "health",
        "startWorkout": "workouts",
        "stopAudio": "audio",
        "stopExtendedRuntimeSession": "runtime",
        "stopHealthUpdates": "health",
        "stopSpeaking": "speech",
        "transferFile": "connectivity",
        "transferUserInfo": "connectivity",
        "updateApplicationContext": "connectivity",
    ]
}
