const fs = require("node:fs");
const path = require("node:path");
const {
  loadConfigPlugins,
  loadAppleTargets,
} = require("./peerDeps");
const { watchTargetConfig, widgetTargetConfig } = require("./targetConfig");
const {
  wireLocalPackage,
  HOST_PRODUCTS,
  WIDGET_PRODUCTS,
} = require("./wireLocalPackage");
const { swiftPackageRelativePath } = require("./resolveSwiftPackage");

const pkg = require("../package.json");

// Unified react-native-watchos config plugin (Phase 1 of docs/publishing.md):
// ONE parameterized, package-ready plugin that composes
//   (a) the @bacons/apple-targets watch (+ widget) target config, generated
//       from options and written to targets/<name>/expo-target.config.js,
//   (b) the SwiftPM host product linking (wireLocalPackage), and
//   (c) the Info.plist deep-merge (via the post-prebuild step, see scripts),
// replacing the demo-specific app/plugins + app/scripts + hand-authored
// expo-target.config.js files.
//
// Target-folder handling — DECISION (Phase 1, option ii):
// @bacons/apple-targets discovers targets by `globSync`-ing
// targets/<name>/expo-target.config.js at config-EVALUATION time (not in a
// mod). So this plugin writes those config files synchronously, in its own
// plugin-function body, BEFORE delegating to apple-targets. The per-target
// SWIFT GLUE (WatchApp.swift, the widget providers/intents) stays authored by
// the consumer in targets/<name>/, because which complications/widgets/intents
// exist is application-specific — generating it generically is Phase 2 ("own
// target creation"), explicitly out of scope here. The plugin owns every
// PARAMETERIZABLE part (target names, App Group, deployment target, bundle-id
// suffixes, HealthKit, infoPlist) so the consumer's targets/ holds only Swift.
//
// peerDeps note: @expo/config-plugins and @bacons/apple-targets are resolved
// from the consumer's project root (peerDeps.js), not required at the top of
// this file — under pnpm the package's own node_modules can't see the
// consumer's copies (and in this monorepo the package is symlinked to js/).

/** @typedef {{
 *   name?: string,
 *   appGroup?: string,
 *   widget?: boolean,
 *   healthKit?: boolean,
 *   deploymentTarget?: string,
 *   appleTeamId?: string,
 *   scheme?: string,
 *   watchBundleSuffix?: string,
 *   widgetBundleSuffix?: string,
 *   infoPlist?: Record<string, unknown>,
 * }} ReactWatchOptions */

/** Apply defaults that reproduce the demo's values exactly. */
function resolveOptions(config, options) {
  const o = options || {};
  const bundleIdentifier = config.ios?.bundleIdentifier;
  if (!bundleIdentifier) {
    throw new Error(
      "[react-native-watchos] ios.bundleIdentifier is required in your Expo " +
        "config (it derives the App Group and the watch bundle id).",
    );
  }
  const name = o.name ?? "React Watch";
  return {
    name,
    widgetName: `${name} Widgets`,
    // bundleId-derived App Group => the demo's group.com.emindeniz99.reactwatch
    // for bundleId com.emindeniz99.reactwatch; overridable.
    appGroup: o.appGroup ?? `group.${bundleIdentifier}`,
    widget: o.widget ?? true,
    healthKit: o.healthKit ?? true,
    deploymentTarget: o.deploymentTarget ?? "10.0",
    appleTeamId: o.appleTeamId ?? config.ios?.appleTeamId,
    scheme: o.scheme ?? "reactwatch",
    watchBundleSuffix: o.watchBundleSuffix ?? ".watch",
    widgetBundleSuffix: o.widgetBundleSuffix ?? ".watch.widgets",
    bundleIdentifier,
    infoPlist: o.infoPlist ?? {},
  };
}

// Renders a target-config object to an `expo-target.config.js` source string.
// apple-targets `require()`s the file, so a plain `module.exports = <object>`
// is enough; JSON.stringify keeps it deterministic and quote-safe.
function renderTargetConfigFile(configObject) {
  return (
    "// AUTO-GENERATED by react-native-watchos config plugin. Do not edit.\n" +
    "// Edit the plugin options in app.json/app.config.js instead.\n" +
    `module.exports = ${JSON.stringify(configObject, null, 2)};\n`
  );
}

// Writes targets/<dir>/expo-target.config.js iff the contents would change, so
// repeated prebuilds don't churn the file (and so a consumer's hand-edits to
// their Swift glue in the same folder are untouched).
function ensureTargetConfigFile(projectRoot, dir, configObject) {
  const targetDir = path.join(projectRoot, "targets", dir);
  fs.mkdirSync(targetDir, { recursive: true });
  const file = path.join(targetDir, "expo-target.config.js");
  const next = renderTargetConfigFile(configObject);
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (current !== next) fs.writeFileSync(file, next);
}

// apple-targets keys its target directory by FOLDER name (it globs the folder,
// derives the pbxproj target from `name`). Keep the demo's folder names so
// existing Swift glue keeps working.
const WATCH_DIR = "watch";
const WIDGET_DIR = "widget";

/** target-name -> SwiftPM products, derived from the resolved options. */
function targetProductsFor(opts) {
  const map = { [opts.name]: HOST_PRODUCTS };
  if (opts.widget) map[opts.widgetName] = WIDGET_PRODUCTS;
  return map;
}

/**
 * Declare the watch app + widget extension to EAS so cloud builds generate and
 * validate their provisioning profiles BEFORE the Xcode project exists, via
 * extra.eas.build.experimental.ios.appExtensions — the documented mechanism; a
 * config plugin that adds extension targets is expected to add this. Idempotent
 * (upsert by targetName). NOTE: not verifiable without an actual EAS build;
 * local Xcode signing is unaffected by it.
 */
function withEasAppExtensions(config, opts) {
  const extra = config.extra ?? {};
  extra.eas = extra.eas ?? {};
  extra.eas.build = extra.eas.build ?? {};
  extra.eas.build.experimental = extra.eas.build.experimental ?? {};
  extra.eas.build.experimental.ios = extra.eas.build.experimental.ios ?? {};
  const ios = extra.eas.build.experimental.ios;
  ios.appExtensions = ios.appExtensions ?? [];
  config.extra = extra;

  const upsert = (entry) => {
    const i = ios.appExtensions.findIndex(
      (e) => e.targetName === entry.targetName,
    );
    if (i >= 0) ios.appExtensions[i] = entry;
    else ios.appExtensions.push(entry);
  };

  upsert({
    targetName: opts.name,
    bundleIdentifier: `${opts.bundleIdentifier}${opts.watchBundleSuffix}`,
    entitlements: {
      "com.apple.security.application-groups": [opts.appGroup],
      ...(opts.healthKit ? { "com.apple.developer.healthkit": true } : {}),
    },
  });
  if (opts.widget) {
    upsert({
      targetName: opts.widgetName,
      bundleIdentifier: `${opts.bundleIdentifier}${opts.widgetBundleSuffix}`,
      entitlements: {
        "com.apple.security.application-groups": [opts.appGroup],
      },
    });
  }
  return config;
}

const withReactWatch = (config, options) => {
  const opts = resolveOptions(config, options);
  const projectRoot = config._internal?.projectRoot ?? process.cwd();
  const { withXcodeProject, createRunOncePlugin, WarningAggregator } =
    loadConfigPlugins(projectRoot);
  const withAppleTargets = loadAppleTargets(projectRoot);

  // The actual plugin work, tagged run-once by name+version (duplicate plugin
  // entries / repeated prebuilds apply it once — the Expo library convention).
  // The on-disk writes and the pbxproj edit are also individually idempotent.
  const inner = createRunOncePlugin(
    (cfg) => {
      // 0. Declare the watch app + widget extension to EAS so cloud builds
      //    provision/sign them before the Xcode project is generated.
      cfg = withEasAppExtensions(cfg, opts);

      // 1. Generate the apple-targets config file(s) on disk BEFORE
      //    apple-targets globs them (synchronously, at evaluation time).
      ensureTargetConfigFile(projectRoot, WATCH_DIR, watchTargetConfig(opts));
      if (opts.widget) {
        ensureTargetConfigFile(
          projectRoot,
          WIDGET_DIR,
          widgetTargetConfig(opts),
        );
      }

      // 2. Let apple-targets discover + inject the targets (its proven,
      //    Phase-1 target creation).
      cfg = withAppleTargets(cfg, { appleTeamId: opts.appleTeamId });

      // 3. Best-effort: pre-register the SwiftPM package reference during
      //    prebuild. apple-targets adds the native targets via its own base
      //    mod, written at a point we can't reliably order this mod after — so
      //    at runtime the targets usually don't exist yet and only the package
      //    *reference* lands here; the product *links* are applied
      //    authoritatively after prebuild by the post-prebuild link step (see
      //    scripts), which reuses the SAME wireLocalPackage. Wrapped so it can
      //    never fail prebuild.
      cfg = withXcodeProject(cfg, (c) => {
        try {
          // XCLocalSwiftPackageReference.relativePath is relative to the dir
          // CONTAINING the .xcodeproj — by Expo convention <projectRoot>/ios.
          const relPath = swiftPackageRelativePath(
            projectRoot,
            path.join(projectRoot, "ios"),
          );
          wireLocalPackage(c.modResults, {
            packagePath: relPath,
            targetProducts: targetProductsFor(opts),
          });
        } catch (error) {
          WarningAggregator.addWarningIOS(
            "react-native-watchos",
            "Could not pre-register the SwiftPM host; the post-prebuild link " +
              `step will still wire it. ${String(error)}`,
          );
        }
        return c;
      });

      return cfg;
    },
    pkg.name,
    pkg.version,
  );

  return inner(config);
};

// Re-exported so the post-prebuild scripts (which run outside Expo) reuse the
// package's logic instead of duplicating it.
withReactWatch.resolveOptions = resolveOptions;
withReactWatch.targetProductsFor = targetProductsFor;
withReactWatch.withEasAppExtensions = withEasAppExtensions;
withReactWatch.WATCH_DIR = WATCH_DIR;
withReactWatch.WIDGET_DIR = WIDGET_DIR;

module.exports = withReactWatch;
