"use strict";

// Pure helpers for `react-native-watchos scaffold` (DX-3): generate the watch
// app's Swift entry point — the one piece every watch consumer writes
// identically. The config plugin generates the expo-target.config.js; this
// generates the matching @main App. Pure (no fs), so it's unit-tested.

/** The identifier core of a target name ("Expo Watch" -> "ExpoWatch"),
 *  falling back to "ReactWatch" when the name has no identifier characters. */
function identifierBase(name) {
  const base = String(name).replace(/[^A-Za-z0-9]/g, "") || "ReactWatch";
  // A Swift identifier can't start with a digit ("2Watch" -> invalid @main
  // struct name), so prefix one when the surviving head is numeric.
  return /^[0-9]/.test(base) ? `App${base}` : base;
}

/** A valid Swift type name derived from the target name.
 *  "Expo Watch" -> "ExpoWatchApp", "React Watch" -> "ReactWatchApp". */
function structName(name) {
  return `${identifierBase(name)}App`;
}

/** The widget bundle's @main struct name: "Expo Watch" -> "ExpoWatchWidgets". */
function widgetStructName(name) {
  return `${identifierBase(name)}Widgets`;
}

/** The @main watch App that embeds ReactWatchRootView with the App Group the
 *  config plugin uses for shared (widget/complication) storage. */
function watchAppSwift({ name, appGroupId }) {
  return `import ReactWatchHost
import SwiftUI

// Starting point generated by \`react-native-watchos scaffold\` — edit freely.
// The watch app is a thin consumer of the ReactWatchHost SwiftPM package: it
// embeds ReactWatchRootView and supplies the App Group used for shared storage
// (widgets / complications). The QuickJS runtime, the SwiftUI interpreter, and
// the native bridges all live in the package.
@main
struct ${structName(name)}: App {
    // Forwards background-refresh tasks (scheduleBackgroundRefresh) to JS's
    // onBackgroundRefresh. Harmless if you never schedule one.
    @WKApplicationDelegateAdaptor(ReactWatchAppDelegate.self) private var appDelegate

    var body: some Scene {
        WindowGroup {
            // OTA updates are refused until you trust a signing key (secure
            // default). Your build script prints the dev key line on first
            // build; production keys come from 'npm run ota:keygen':
            //   ota: .init(signerPublicKeys: ["<keyId>": "<publicKeyBase64>"])
            ReactWatchRootView(appGroupId: "${appGroupId}")
        }
    }
}
`;
}

/** The @main WidgetBundle every widget consumer writes — a thin consumer of the
 *  ReactWatchWidget package. Each widget pairs a `kind` (registered on the JS
 *  side via registerWidget) with the package's ReactTimelineProvider +
 *  reactWidgetView; the package owns the interpreter, the timeline logic, and
 *  the extension's QuickJS runtime. The App Group must match the watch app's. */
function widgetBundleSwift({ name, appGroupId }) {
  return `import ReactWatchWidget
import SwiftUI
import WidgetKit

// Starting point generated by \`react-native-watchos scaffold\` — edit freely.
// The widget extension is a thin consumer of the ReactWatchWidget package: each
// widget pairs a \`kind\` (registered on the JS side with registerWidget) with the
// package's ReactTimelineProvider + reactWidgetView, which render the React tree
// your JS publishes to the shared App Group. Add one widget per kind. A
// configurable widget (a list/option picker on the watch face) writes its own
// AppIntentTimelineProvider on top of the package's reactTimeline/
// reactSnapshotEntry helpers — see the demo (app/targets/widget) and the README.
@main
struct ${widgetStructName(name)}: WidgetBundle {
    var body: some Widget {
        ExampleWidget()
    }
}

struct ExampleWidget: Widget {
    // Must match a \`kind\` you registered in your widget JS entry (registerWidget).
    let kind = "example"

    var body: some WidgetConfiguration {
        StaticConfiguration(
            kind: kind,
            provider: ReactTimelineProvider(kind: kind, appGroupId: "${appGroupId}")
        ) { entry in
            reactWidgetView(entry, appGroupId: "${appGroupId}")
        }
        .configurationDisplayName("Example")
        .description("A React-rendered complication.")
        .supportedFamilies([
            .accessoryCircular,
            .accessoryRectangular,
            .accessoryInline,
        ])
    }
}
`;
}

module.exports = {
  structName,
  widgetStructName,
  watchAppSwift,
  widgetBundleSwift,
};
