"use strict";

// Pure helpers for `react-native-watchos scaffold` (DX-3): generate the watch
// app's Swift entry point — the one piece every watch consumer writes
// identically. The config plugin generates the expo-target.config.js; this
// generates the matching @main App. Pure (no fs), so it's unit-tested.

/** A valid Swift type name derived from the target name.
 *  "Expo Watch" -> "ExpoWatchApp", "React Watch" -> "ReactWatchApp". */
function structName(name) {
  const id = String(name).replace(/[^A-Za-z0-9]/g, "");
  return `${id || "ReactWatch"}App`;
}

/** The @main watch App that embeds ReactWatchRootView with the App Group the
 *  config plugin uses for shared (widget/complication) storage. */
function watchAppSwift({ name, appGroupId }) {
  return `import ReactWatchHost
import SwiftUI

// Starting point generated by \`react-native-watchos scaffold\` — edit freely.
// The watch app is a thin consumer of the ReactWatchHost SwiftPM package: it
// embeds ReactWatchRootView and supplies the App Group used for shared storage
// (widgets / complications). The QuickJS runtime, the SwiftUI interpreter, and
// the native bridges all live in the package.
@main
struct ${structName(name)}: App {
    var body: some Scene {
        WindowGroup {
            ReactWatchRootView(appGroupId: "${appGroupId}")
        }
    }
}
`;
}

module.exports = { structName, watchAppSwift };
