import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  bridgeProtocol,
  components,
  type HostMethod,
  hostMethods,
} from "../codegen/schema.ts";
import { root } from "./config.ts";

// Emits docs/api/capabilities.md FROM codegen/schema.ts (M12): the component
// vocabulary + widget-support levels and the host-method/feature matrix are
// generated, not hand-written, so the published capability tables can't drift
// from the contract the tests pin (component-contract.test.ts /
// codegen.test.ts). Run via `npm run docs:api` (with typedoc).

const componentRows = components
  .map(
    (c) => `| \`${c.name}\` | ${c.widget === "full" ? "full" : "degraded"} |`,
  )
  .join("\n");

const byFeature = new Map<string, HostMethod[]>();
for (const m of hostMethods) {
  const list = byFeature.get(m.feature) ?? [];
  list.push(m);
  byFeature.set(m.feature, list);
}
const methodRows = [...byFeature.entries()]
  .map(([feature, methods]) =>
    methods
      .map(
        (m, i) =>
          `| ${i === 0 ? `\`${feature}\`` : ""} | \`${m.name}\` | ` +
          `${m.targets.join(", ")} | ${m.via === "invoke" ? "invoke" : "direct"} | ${m.since} |`,
      )
      .join("\n"),
  )
  .join("\n");

const doc = `<!-- AUTO-GENERATED by scripts/gen-capability-table.ts from
     codegen/schema.ts — do not edit; run \`npm run docs:api\`. -->

# Capability tables

Generated from [\`codegen/schema.ts\`](../../js/codegen/schema.ts) — the
single source of truth the wire/codegen drift tests pin — so these tables
cannot disagree with the shipped contract. Bridge protocol: **${bridgeProtocol}**.

## Components (${components.length})

"full" renders identically in the widget/complication interpreter; "degraded"
renders a reduced form there (interaction, live ticking, and presentation
surfaces don't exist in WidgetKit).

| Component | Widget support |
|---|---|
${componentRows}

## Host methods (${hostMethods.length}) by capability feature

An OTA bundle's \`requiredFeatures\` must be a subset of the binary's
feature set (ARCH-01); \`since\` is the bridge-protocol version the method
appeared in. "invoke" methods route through the generic invoke channel
(SD-1); "direct" methods are installed as their own \`__host\` functions.

| Feature | Method | Targets | Via | Since |
|---|---|---|---|---|
${methodRows}
`;

const out = join(root, "..", "docs", "api", "capabilities.md");
writeFileSync(out, doc);
console.log(`wrote ${out}`);
