import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { buildBundles } from "../esbuild/preset.mts";

// Guards the packaging contract: every path the published package promises
// (exports targets, main/types, the `files` whitelist) must exist AND be
// committed to git. The esbuild preset was once present on disk but gitignored,
// so its export broke on a fresh clone — present-on-disk hid it, git-tracked
// catches it. src/ ships as source (bundler-consumed), but the Node-LOADED
// surfaces (bin/plugin/esbuild entries) are COMPILED to dist-node/ by
// scripts/build-node.ts (Node refuses type stripping under node_modules) —
// dist-node/ is gitignored and generated by `prepare`, so its paths are
// checked for existence after a build instead of git tracking.

const jsRoot = join(__dirname, "..");

/** Generated (gitignored) compiled output — see scripts/build-node.ts. */
const isGenerated = (relPath: string) =>
  relPath === "dist-node" ||
  relPath.replace(/^\.\//, "").startsWith("dist-node/");

beforeAll(() => {
  // Build dist-node/ the same way `prepare` does, so the exports/files checks
  // below see exactly what a publish would ship.
  execFileSync(
    process.execPath,
    ["--experimental-strip-types", "scripts/build-node.ts"],
    { cwd: jsRoot, stdio: "pipe" },
  );
}, 60_000);
const pkg = JSON.parse(readFileSync(join(jsRoot, "package.json"), "utf8")) as {
  main: string;
  types: string;
  exports: unknown;
  files: string[];
};

function isTracked(relPath: string): boolean {
  try {
    execFileSync("git", ["ls-files", "--error-unmatch", relPath], {
      cwd: jsRoot,
      stdio: "pipe",
    });
    return true;
  } catch {
    return false;
  }
}

/** Every concrete file an exports conditions map points at. */
function exportTargets(): string[] {
  const out: string[] = [];
  const walk = (node: unknown): void => {
    if (typeof node === "string") {
      if (node.startsWith("./")) out.push(node);
    } else if (node && typeof node === "object") {
      for (const value of Object.values(node)) walk(value);
    }
  };
  walk(pkg.exports);
  return [...new Set(out)];
}

describe("packaging contract", () => {
  it("every exports target exists and is committed (or generated)", () => {
    for (const target of exportTargets()) {
      expect(existsSync(join(jsRoot, target)), `${target} missing`).toBe(true);
      if (!isGenerated(target)) {
        expect(isTracked(target), `${target} is not tracked by git`).toBe(true);
      }
    }
  });

  it("main and types point at committed files", () => {
    for (const field of [pkg.main, pkg.types]) {
      expect(isTracked(field), `${field} is not tracked by git`).toBe(true);
    }
  });

  it("every `files` entry is committed (or generated)", () => {
    for (const entry of pkg.files) {
      if (isGenerated(entry)) {
        expect(
          existsSync(join(jsRoot, entry)),
          `generated files entry "${entry}" missing — run pnpm build:node`,
        ).toBe(true);
        continue;
      }
      const tracked = execFileSync("git", ["ls-files", entry], {
        cwd: jsRoot,
        encoding: "utf8",
      }).trim();
      expect(tracked, `files entry "${entry}" has no committed files`).not.toBe(
        "",
      );
    }
  });
});

// DX-4: the published tarball must ship what a real `npm i` consumer needs to
// integrate — the SwiftPM host SOURCES (so the XCLocalSwiftPackageReference
// resolves from node_modules), the config plugin (incl. the in-prebuild wiring),
// and the CLI. `npm pack --dry-run` reports the exact file list npm would ship,
// catching a `files`/.npmignore mistake that "committed to git" alone wouldn't.
describe("published tarball contents (DX-4)", () => {
  const packedFiles = (): string[] => {
    // --ignore-scripts: `prepare` (build-node) already ran in beforeAll; a
    // second run here would only slow the test and risk polluting the JSON.
    const out = execFileSync(
      "npm",
      ["pack", "--dry-run", "--json", "--ignore-scripts"],
      {
        cwd: jsRoot,
        encoding: "utf8",
      },
    );
    const report = JSON.parse(out) as Array<{
      files?: Array<{ path: string }>;
    }>;
    return (report[0]?.files ?? []).map((f) => f.path);
  };

  // `npm pack --dry-run` walks and stats the whole package tree — under
  // full-suite load it can blow vitest's default 5s test timeout, so these
  // two tests get an explicit generous one.
  const packTimeout = { timeout: 30_000 };

  it(
    "ships the Swift host sources, the plugin, and the CLI",
    packTimeout,
    () => {
      const files = packedFiles();
      for (const required of [
        "swift/Package.swift",
        "app.plugin.js",
        "plugin/index.cts",
        "plugin/withNativeWiring.cts",
        "plugin/scaffold.cts",
        "bin/react-watchos.cts",
        "esbuild/preset.mts",
        // The compiled Node-loaded surfaces a registry install actually runs
        // (Node refuses type stripping under node_modules).
        "dist-node/react-watchos.cjs",
        "dist-node/plugin.cjs",
        "dist-node/link-swift-package.cjs",
        "dist-node/merge-target-infoplist.cjs",
        "dist-node/preset.mjs",
        "dist-node/manifest.mjs",
      ]) {
        expect(files, `tarball is missing ${required}`).toContain(required);
      }
      // The SwiftPM ref resolves to <pkg>/swift, so the Sources must be in the
      // tarball (not just Package.swift) — at least the host module.
      const swiftSources = files.filter(
        (f) => f.startsWith("swift/Sources/") && f.endsWith(".swift"),
      );
      expect(swiftSources.length).toBeGreaterThan(0);
      expect(
        swiftSources.some((f) => f.includes("ReactWatchHost")),
        "tarball is missing the ReactWatchHost Swift sources",
      ).toBe(true);
    },
  );

  it(
    "does not ship build artifacts (.build) or tests-only noise",
    packTimeout,
    () => {
      const files = packedFiles();
      expect(files.some((f) => f.includes("swift/.build/"))).toBe(false);
    },
  );
});

// `build --symbols` shipped while its reader lived in scripts/ (not in
// `files`), so a registry install could write a symbol store and nothing it
// installed could read one. This drives the COMPILED bin — the file
// package.json's `bin` points at, which the beforeAll above just built — not
// the .cts source symbolicate-cli.test.ts spawns, so "the subcommand exists
// in the source" cannot stand in for "it ships". It lives here rather than
// next to the other symbolicate tests because this is the one file that
// builds dist-node/, and build-node.ts starts by deleting it: a reader in
// another file would race that rm -> rebuild under vitest's parallel workers.
describe("compiled CLI (what a registry install runs)", () => {
  const compiledBin = join(jsRoot, "dist-node/react-watchos.cjs");
  const sourceBin = join(jsRoot, "bin/react-watchos.cts");

  it("symbolicate is reachable from dist-node/react-watchos.cjs", async () => {
    const dir = mkdtempSync(join(tmpdir(), "rnw-pack-symcli-"));
    const entry = join(dir, "entry.ts");
    writeFileSync(
      entry,
      "function shoppingListProbe() {\n  return 1;\n}\n" +
        "globalThis.__probeGlobal = shoppingListProbe() + 1;\n",
    );
    const outfile = join(dir, "bundle.js");
    const symbols = join(dir, "symbols");
    const [built] = await buildBundles([{ name: "app", entry, outfile }], {
      symbols,
    });
    const releaseId = built?.releaseId ?? "";
    expect(releaseId).not.toBe("");

    // A stack in the shape the vendored quickjs-ng emits, pointing at the
    // probe's declaration in the REAL minified bundle (located through the
    // one identifier minification cannot rename). Columns are 1-based.
    const code = readFileSync(outfile, "utf8");
    const call = /globalThis\.__probeGlobal\s*=\s*([A-Za-z_$][\w$]*)\s*\(/.exec(
      code,
    );
    const minified = call?.[1] ?? "";
    expect(minified).not.toBe("");
    const index = code.indexOf(`function ${minified}(`) + "function ".length;
    const stack =
      "Error: boom\n" +
      `    at ${minified} (bundle.js:1:${index + 1})\n` +
      "    at <anonymous> (bundle.js:1:1)\n";

    const args = ["symbolicate", "--symbols", symbols, "--release", releaseId];
    const shipped = spawnSync(process.execPath, [compiledBin, ...args], {
      input: stack,
      encoding: "utf8",
    });
    expect(shipped.status, shipped.stderr).toBe(0);
    expect(shipped.stdout).toContain("at shoppingListProbe (");
    expect(shipped.stdout).toContain("entry.ts:1:10");

    // …and byte for byte what the source the rest of the suite drives prints.
    const fromSource = spawnSync(
      process.execPath,
      ["--experimental-strip-types", sourceBin, ...args],
      { input: stack, encoding: "utf8" },
    );
    expect(shipped.stdout).toBe(fromSource.stdout);
  }, 60_000);
});
