import ReactWatchHost
import SwiftUI

// Starting point generated by `react-watchos scaffold` — edit freely.
// The watch app is a thin consumer of the ReactWatchHost SwiftPM package: it
// embeds ReactWatchRootView and supplies the App Group used for shared storage
// (widgets / complications). The QuickJS runtime, the SwiftUI interpreter, and
// the native bridges all live in the package.
@main
struct ExpoWatchApp: App {
    // Delivers scheduled background refreshes to JS's onBackgroundRefresh.
    @WKApplicationDelegateAdaptor(ReactWatchAppDelegate.self) private var appDelegate

    var body: some Scene {
        WindowGroup {
            // OTA updates are refused until you trust a signing key (secure
            // default). `npm run build:targets` prints your dev key's line on
            // first build (persisted at .ota-dev-key.json, gitignored):
            //   ota: .init(signerPublicKeys: ["<keyId>": "<publicKeyBase64>"])
            //
            // `policy` is least privilege for OTA bundles (ARCH-07): a signed
            // bundle is arbitrary code with every capability this binary
            // installs, so the APP decides which of them are authorized.
            // This allowlist mirrors the bundle's declared contract
            // (`requiredFeatures` in scripts/build-targets.mjs) — no health, no
            // BLE, no AI, no push, even though the package can back them.
            // Turning one on takes a native release, never just a new bundle.
            ReactWatchRootView(
                appGroupId: "group.com.example.expowatch",
                policy: .allow(["connectivity", "network", "ota", "storage", "widgets"])
            )
        }
    }
}
