import ReactWatchHost
import SwiftUI

// Starting point generated by `react-native-watchos scaffold` — edit freely.
// The watch app is a thin consumer of the ReactWatchHost SwiftPM package: it
// embeds ReactWatchRootView and supplies the App Group used for shared storage
// (widgets / complications). The QuickJS runtime, the SwiftUI interpreter, and
// the native bridges all live in the package.
@main
struct ExpoWatchApp: App {
    var body: some Scene {
        WindowGroup {
            // OTA updates are refused until you trust a signing key (secure
            // default). `npm run build:targets` prints your dev key's line on
            // first build (persisted at .ota-dev-key.json, gitignored):
            //   ota: .init(signerPublicKeys: ["<keyId>": "<publicKeyBase64>"])
            ReactWatchRootView(appGroupId: "group.com.example.expowatch")
        }
    }
}
