import ReactWatchHost
import SwiftUI

// Starting point generated by `react-native-watchos scaffold` — edit freely.
// The watch app is a thin consumer of the ReactWatchHost SwiftPM package: it
// embeds ReactWatchRootView and supplies the App Group used for shared storage
// (widgets / complications). The QuickJS runtime, the SwiftUI interpreter, and
// the native bridges all live in the package.
@main
struct ExpoWatchApp: App {
    var body: some Scene {
        WindowGroup {
            ReactWatchRootView(appGroupId: "group.com.example.expowatch")
        }
    }
}
