#if canImport(CryptoKit)
import CryptoKit
import Foundation
import ReactWatchSupport
import XCTest

/// CR-4 / CR-17 interop: a signature produced by scripts/ota-sign.mjs (Node
/// Ed25519 over "v1:<keyId>:<version>:<bundle>") must verify on the watch with
/// CryptoKit over UpdatePlan.signedMessage. This static vector was produced by
/// the Node signer; if the script's message format and Swift's signedMessage
/// ever drift apart, this test fails — catching a break that would otherwise
/// only surface as "every OTA update rejected" on-device. CryptoKit-only
/// (skipped on Linux).
final class OTASigningInteropTests: XCTestCase {
    // Generated by Node: ed25519, message "v1:k1A2b3C4:1:globalThis.__x=42;".
    private let keyId = "k1A2b3C4"
    private let publicKeyBase64 = "xrgFlN2+VHSyDramStfr+D6vufoGNxzvVP4FgfAzJeU="
    private let signatureBase64 =
        "9ZKgRY0SG/IDKXr+y+xBxKJbktkI7uIVIydwDKRt7QdKw0rUecpsTPitOzn6WVbduc968G7uTji9VKp52cwDDg=="

    func testNodeSignedBundleVerifiesWithUpdatePlanMessage() throws {
        let key = try Curve25519.Signing.PublicKey(
            rawRepresentation: XCTUnwrap(Data(base64Encoded: publicKeyBase64))
        )
        let signature = try XCTUnwrap(Data(base64Encoded: signatureBase64))
        // The exact bytes the host verifies — built from UpdatePlan, not a string
        // literal, so a change to signedMessage's format breaks this test.
        let message = try XCTUnwrap(
            UpdatePlan(
                js: "globalThis.__x=42;", keyId: keyId, version: 1, signature: nil
            ).signedMessage()
        )

        XCTAssertTrue(
            key.isValidSignature(signature, for: message),
            "a Node-signed bundle must verify with CryptoKit")
        // The version is inside the signed bytes — a mismatched version fails.
        let tamperedVersion = try XCTUnwrap(
            UpdatePlan(
                js: "globalThis.__x=42;", keyId: keyId, version: 2, signature: nil
            ).signedMessage()
        )
        XCTAssertFalse(key.isValidSignature(signature, for: tamperedVersion))
        // The keyId is inside the signed bytes too (CX-007) — a swapped key id
        // fails, so it can't be used to steer the host to a different key.
        let tamperedKeyId = try XCTUnwrap(
            UpdatePlan(
                js: "globalThis.__x=42;", keyId: "otherKey", version: 1, signature: nil
            ).signedMessage()
        )
        XCTAssertFalse(key.isValidSignature(signature, for: tamperedKeyId))
    }
}
#endif
