#if canImport(CryptoKit)
import CryptoKit
import Foundation
import ReactWatchSupport
import XCTest

/// CR-4 / CR-17 interop: a signature produced by the Node signer
/// (js/esbuild/manifest.mts signManifest, Ed25519 over
/// "v3:<keyId>:<version>:<sequence>:<expiresAt>:<bundle>") must verify on the
/// watch with CryptoKit over UpdatePlan.signedMessage. This static vector was
/// produced by Node; if the signer's message format and Swift's signedMessage
/// ever drift apart, this test fails — catching a break that would otherwise
/// only surface as "every OTA update rejected" on-device. CryptoKit-only
/// (skipped on Linux). The only real-bytes check: the sequencer suite stubs
/// `verify`.
final class OTASigningInteropTests: XCTestCase {
    // Generated by Node (one-off, private key discarded):
    //   node --input-type=module -e '
    //     import { generateKeyPairSync, sign } from "node:crypto";
    //     const m = Buffer.from("v3:k1A2b3C4:1:1700000000:0:globalThis.__x=42;");
    //     const { publicKey, privateKey } = generateKeyPairSync("ed25519");
    //     const x = publicKey.export({ format: "jwk" }).x;
    //     console.log(Buffer.from(x, "base64url").toString("base64"));
    //     console.log(sign(null, m, privateKey).toString("base64"));'
    private let keyId = "k1A2b3C4"
    private let publicKeyBase64 = "VSTHNoyFiAtKw/ZWt60RM27qqDrYmaFWNpT5EP2+ap0="
    private let signatureBase64 =
        "OyDQQnXZBnhCBV1bE3C7s50S3+D/5/I9o24OWpu4YTzqNOV9RBzFweRF7IVKJwI7CHqYa3UUb57J/wlDSUcDDA=="
    private let sequence = 1_700_000_000

    func testNodeSignedBundleVerifiesWithUpdatePlanMessage() throws {
        let key = try Curve25519.Signing.PublicKey(
            rawRepresentation: XCTUnwrap(Data(base64Encoded: publicKeyBase64))
        )
        let signature = try XCTUnwrap(Data(base64Encoded: signatureBase64))
        // The exact bytes the host verifies — built from UpdatePlan, not a string
        // literal, so a change to signedMessage's format breaks this test.
        let message = try XCTUnwrap(
            UpdatePlan(
                js: "globalThis.__x=42;", keyId: keyId, version: 1, signature: nil,
                sequence: sequence
            ).signedMessage()
        )

        XCTAssertTrue(
            key.isValidSignature(signature, for: message),
            "a Node-signed bundle must verify with CryptoKit")
        // The version is inside the signed bytes — a mismatched version fails.
        let tamperedVersion = try XCTUnwrap(
            UpdatePlan(
                js: "globalThis.__x=42;", keyId: keyId, version: 2, signature: nil,
                sequence: sequence
            ).signedMessage()
        )
        XCTAssertFalse(key.isValidSignature(signature, for: tamperedVersion))
        // The keyId is inside the signed bytes too (CX-007) — a swapped key id
        // fails, so it can't be used to steer the host to a different key.
        let tamperedKeyId = try XCTUnwrap(
            UpdatePlan(
                js: "globalThis.__x=42;", keyId: "otherKey", version: 1, signature: nil,
                sequence: sequence
            ).signedMessage()
        )
        XCTAssertFalse(key.isValidSignature(signature, for: tamperedKeyId))
        // The expiry is inside the signed bytes too (the revocation lever) —
        // a bundle signed with no expiry can't be relabelled with one, and
        // vice versa: an attacker can't strip an expiry off a lapsed bundle.
        let tamperedExpiry = try XCTUnwrap(
            UpdatePlan(
                js: "globalThis.__x=42;", keyId: keyId, version: 1, signature: nil,
                expiresAt: 4_102_444_800, sequence: sequence
            ).signedMessage()
        )
        XCTAssertFalse(key.isValidSignature(signature, for: tamperedExpiry))
        // The publish sequence is inside the signed bytes (scheme v3) — a
        // re-served older build can't be relabelled past the device's mark.
        let tamperedSequence = try XCTUnwrap(
            UpdatePlan(
                js: "globalThis.__x=42;", keyId: keyId, version: 1, signature: nil,
                sequence: sequence - 1
            ).signedMessage()
        )
        XCTAssertFalse(key.isValidSignature(signature, for: tamperedSequence))
    }
}
#endif
