#if canImport(CryptoKit)
import CryptoKit
import Foundation
import ReactWatchSupport
import XCTest

// CR-4 / CR-17 interop: a signature produced by scripts/ota-sign.mjs (Node
// Ed25519 over "v1:<version>:<bundle>") must verify on the watch with CryptoKit
// over UpdatePlan.signedMessage. This static vector was produced by the Node
// signer; if the script's message format and Swift's signedMessage ever drift
// apart, this test fails — catching a break that would otherwise only surface
// as "every OTA update rejected" on-device. CryptoKit-only (skipped on Linux).
final class OTASigningInteropTests: XCTestCase {
    // Generated by Node: ed25519, message "v1:1:globalThis.__x=42;".
    private let publicKeyBase64 = "qq2PAyofUm1q2rvz/pNQo41Hdg1VPz56T67NnefmljA="
    private let signatureBase64 =
        "+0E5wXqSg9bvQWG8/zy8MTDgmGmkhfQ+y0XsDFpdSv/r1w5LSPXn1lc4+GNhlwPB+REblAO62UeS3hOP405dAw=="

    func testNodeSignedBundleVerifiesWithUpdatePlanMessage() throws {
        let key = try Curve25519.Signing.PublicKey(
            rawRepresentation: XCTUnwrap(Data(base64Encoded: publicKeyBase64)))
        let signature = try XCTUnwrap(Data(base64Encoded: signatureBase64))
        // The exact bytes the host verifies — built from UpdatePlan, not a string
        // literal, so a change to signedMessage's format breaks this test.
        let message = try XCTUnwrap(
            UpdatePlan(js: "globalThis.__x=42;", version: 1, signature: nil).signedMessage())

        XCTAssertTrue(key.isValidSignature(signature, for: message),
                      "a Node-signed bundle must verify with CryptoKit")
        // The version is inside the signed bytes — a mismatched version fails.
        let tampered = try XCTUnwrap(
            UpdatePlan(js: "globalThis.__x=42;", version: 2, signature: nil).signedMessage())
        XCTAssertFalse(key.isValidSignature(signature, for: tampered))
    }
}
#endif
