import ReactWatchWidget
import SwiftUI
import WidgetKit

// Starting point generated by `react-native-watchos scaffold` — edit freely.
// The widget extension is a thin consumer of the ReactWatchWidget package: each
// widget pairs a `kind` (registered on the JS side with registerWidget) with the
// package's ReactTimelineProvider + reactWidgetView, which render the React tree
// your JS publishes to the shared App Group. Add one widget per kind. A
// configurable widget (a list/option picker on the watch face) writes its own
// AppIntentTimelineProvider on top of the package's reactTimeline/
// reactSnapshotEntry helpers — see the demo (app/targets/widget) and the README.
@main
struct ExpoWatchWidgets: WidgetBundle {
    var body: some Widget {
        ExampleWidget()
    }
}

struct ExampleWidget: Widget {
    // Must match a `kind` you registered in your widget JS entry (registerWidget).
    let kind = "example"

    var body: some WidgetConfiguration {
        StaticConfiguration(
            kind: kind,
            provider: ReactTimelineProvider(kind: kind, appGroupId: "group.com.example.expowatch")
        ) { entry in
            reactWidgetView(entry)
        }
        .configurationDisplayName("Example")
        .description("A React-rendered complication.")
        .supportedFamilies([
            .accessoryCircular,
            .accessoryRectangular,
            .accessoryInline,
        ])
    }
}
