import ReactWatchWidget
import SwiftUI
import WidgetKit

// Generated by `react-native-watchos scaffold`, then edited to add a second
// widget. The widget extension is a thin consumer of the ReactWatchWidget
// package: each widget pairs a `kind` (registered on the JS side with
// registerWidget) with the package's ReactTimelineProvider + reactWidgetView,
// which render the React tree your JS publishes to the shared App Group.
//
// Note both widgets below have IDENTICAL Swift — "static" vs "live data" is a
// JS concern (whether the render reads shared Storage and the app publishes
// updates; see watch-ui/widgets.tsx). A configurable widget (a picker on the
// watch face) is the only kind that writes its own AppIntentTimelineProvider —
// see the demo (app/targets/widget) and the README.

private let appGroup = "group.com.example.expowatch"

@main
struct ExpoWatchWidgets: WidgetBundle {
    var body: some Widget {
        ExampleWidget()
        TapsWidget()
    }
}

// Static: constant content the extension renders on its own.
struct ExampleWidget: Widget {
    let kind = "example"  // matches registerWidget("example") in widgets.tsx

    var body: some WidgetConfiguration {
        StaticConfiguration(
            kind: kind,
            provider: ReactTimelineProvider(kind: kind, appGroupId: appGroup)
        ) { entry in
            reactWidgetView(entry, appGroupId: appGroup)
        }
        .configurationDisplayName("Example")
        .description("A static React-rendered complication.")
        .supportedFamilies([
            .accessoryCircular,
            .accessoryRectangular,
            .accessoryInline,
        ])
    }
}

// Live data: shows the tap count the app writes to shared Storage (the JS
// render reads it; the app calls publishWidgets() to refresh).
struct TapsWidget: Widget {
    let kind = "taps"  // matches registerWidget("taps") in widgets.tsx

    var body: some WidgetConfiguration {
        StaticConfiguration(
            kind: kind,
            provider: ReactTimelineProvider(kind: kind, appGroupId: appGroup)
        ) { entry in
            reactWidgetView(entry, appGroupId: appGroup)
        }
        .configurationDisplayName("Taps")
        .description("Your tap count, updated from the watch app.")
        .supportedFamilies([
            .accessoryCircular,
            .accessoryRectangular,
            .accessoryInline,
        ])
    }
}
