// Renders codegen/schema.mjs into Swift models (watch + widget) and TS wire
// types. Run `npm run codegen` after editing the schema. `--check` exits
// non-zero if the committed output is stale (used by the drift test).

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { hostMethods, node, structs, tsOnly } from "./schema.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const banner = () =>
  `// @generated by js/codegen/generate.mjs — DO NOT EDIT.\n// Run \`npm run codegen\` after editing js/codegen/schema.mjs.\n`;

// --- Swift -----------------------------------------------------------------

const JSON_VALUE_SWIFT = `enum JSONValue: Codable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case array([JSONValue])
    case object([String: JSONValue])
    case null

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let bool = try? container.decode(Bool.self) {
            self = .bool(bool)
        } else if let number = try? container.decode(Double.self) {
            self = .number(number)
        } else if let string = try? container.decode(String.self) {
            self = .string(string)
        } else if let array = try? container.decode([JSONValue].self) {
            self = .array(array)
        } else if let object = try? container.decode([String: JSONValue].self) {
            self = .object(object)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container, debugDescription: "Unsupported JSON value")
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}`;

const nodeSwift =
  () => `struct ${node.swift}: Codable, Equatable, Identifiable {
    let id: Int
    let type: String
    let props: [String: JSONValue]
    let children: [${node.swift}]

    func string(_ key: String) -> String? {
        if case .string(let value)? = props[key] { return value }
        return nil
    }

    func double(_ key: String) -> Double? {
        if case .number(let value)? = props[key] { return value }
        return nil
    }

    func bool(_ key: String) -> Bool? {
        if case .bool(let value)? = props[key] { return value }
        return nil
    }

    func stringArray(_ key: String) -> [String]? {
        guard case .array(let values)? = props[key] else { return nil }
        return values.compactMap {
            if case .string(let value) = $0 { return value }
            return nil
        }
    }
}`;

function swiftStruct(def) {
  const lines = [`struct ${def.swift}: Codable, Equatable {`];
  for (const f of def.fields) {
    if (f.doc) lines.push(`    /// ${f.doc}`);
    lines.push(`    let ${f.name}: ${f.swift}`);
  }
  for (const computed of def.swiftComputed ?? []) {
    lines.push("");
    lines.push(`    ${computed}`);
  }
  lines.push("}");
  return lines.join("\n");
}

function swiftModel(target) {
  const parts = [
    banner(),
    "import Foundation",
    "",
    JSON_VALUE_SWIFT,
    "",
    nodeSwift(),
  ];
  for (const def of structs) {
    if (def.targets.includes(target)) parts.push("", swiftStruct(def));
  }
  return `${parts.join("\n")}\n`;
}

// --- TypeScript ------------------------------------------------------------

function tsInterface(def) {
  const lines = [];
  if (def.doc) lines.push(`/** ${def.doc} */`);
  lines.push(`export interface ${def.ts} {`);
  for (const f of def.fields) {
    const opt = f.optional ? "?" : "";
    const doc = f.doc ? ` // ${f.doc}` : "";
    lines.push(`  ${f.name}${opt}: ${f.ts};${doc}`);
  }
  lines.push("}");
  return lines.join("\n");
}

function tsModel() {
  const parts = [
    banner(),
    "/* eslint-disable */",
    "export type JSONValue =",
    "  | string | number | boolean | JSONValue[]",
    "  | { [key: string]: JSONValue } | null;",
    "",
    `export interface ${node.ts} {`,
    "  id: number;",
    "  type: string;",
    "  props: Record<string, unknown>;",
    `  children: ${node.ts}[];`,
    "}",
  ];
  for (const def of [...structs, ...tsOnly]) parts.push("", tsInterface(def));
  const manifest = JSON.stringify(
    hostMethods.map((m) => ({ name: m.name, targets: m.targets })),
  );
  parts.push(
    "",
    "/** Native bridge methods and which runtime installs each. */",
    `export const HOST_METHODS = ${manifest} as const;`,
  );
  return `${parts.join("\n")}\n`;
}

// --- Outputs ---------------------------------------------------------------

const outputs = [
  ["../app/targets/watch/Generated/WireModel.swift", swiftModel("watch")],
  ["../app/targets/widget/Generated/WireModel.swift", swiftModel("widget")],
  ["src/generated/wire.ts", tsModel()],
];

const check = process.argv.includes("--check");
let stale = 0;
for (const [rel, content] of outputs) {
  const path = join(root, rel);
  if (check) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      /* missing */
    }
    if (current !== content) {
      console.error(`stale: ${rel}`);
      stale += 1;
    }
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${rel}`);
  }
}
if (check && stale > 0) {
  console.error(
    `\n${stale} generated file(s) out of date — run \`npm run codegen\`.`,
  );
  process.exit(1);
}
