// Renders codegen/schema.ts into Swift models (watch + widget) and TS wire
// types. Run `npm run codegen` after editing the schema. `--check` exits
// non-zero if the committed output is stale (used by the drift test).

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type ArgType,
  bridgeProtocol,
  components,
  healthQuantityTypes,
  type HostArg,
  type HostMethod,
  hostMethods,
  invokeShapes,
  node,
  type ReturnType,
  type StructDef,
  structs,
  type TsOnlyDef,
  tsOnly,
  wireVersion,
  type WireTarget,
  workoutActivityTypes,
} from "./schema.ts";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// Generated Swift is piped through Apple's swift-format with the repo's
// `.swift-format` config, so the output is formatter-clean and never needs
// excluding from a `swift format` run (the generated TS is biome-ignored
// separately). Needs the toolchain's `swift format` (bundled with Xcode 16+ /
// Swift 6) — the same tool that formats the hand-written sources.
const swiftFormatConfig = join(root, "..", ".swift-format");
// A formatter can "succeed" with empty stdout on an incompatible CLI — and
// silently emptied @generated files would then land on disk. Fail loud:
// formatting never shrinks real code to under half its size.
const implausiblySmall = (formatted: string, source: string) =>
  formatted.trim().length < source.trim().length / 2;
function formatSwift(source: string) {
  try {
    // `-` reads the source from stdin (implicit stdin is deprecated) — but
    // swift-format 6.0 on Linux writes NOTHING for `-` (exit 0, empty stdout)
    // while implicit stdin works, so fall back to it before failing.
    let formatted = execFileSync(
      "swift",
      ["format", "--configuration", swiftFormatConfig, "-"],
      { input: source, encoding: "utf8" },
    );
    if (implausiblySmall(formatted, source)) {
      formatted = execFileSync(
        "swift",
        ["format", "--configuration", swiftFormatConfig],
        { input: source, encoding: "utf8" },
      );
    }
    if (implausiblySmall(formatted, source)) {
      throw new Error(
        "swift format produced implausibly small output " +
          `(${formatted.length} bytes from ${source.length})`,
      );
    }
    return formatted;
  } catch (error) {
    throw new Error(
      "swift-format failed to format generated Swift — is the Swift toolchain " +
        `installed? \`swift format\` is required by codegen.\n${
          (error as Error).message
        }`,
    );
  }
}
const banner = () =>
  `// @generated by js/codegen/generate.ts — DO NOT EDIT.\n// Run \`npm run codegen\` after editing js/codegen/schema.ts.\n`;

/** The unique capability features a native `target` provides (ARCH-01),
 *  derived from the host methods it installs. */
const featuresFor = (target: WireTarget) =>
  [
    ...new Set(
      hostMethods
        .filter((m) => m.targets.includes(target))
        .map((m) => m.feature),
    ),
  ].sort();

// --- Host bridge (CX-023) --------------------------------------------------
// The synchronous `__host` surface is generated end-to-end from the method
// signatures: the TS `QuickJSHostGlobal`, the Swift `HostBridge` callbacks, the
// C trampolines, and the install table. `via: "invoke"` methods are routed
// through the generic channel, so they're not part of this surface.

/** Methods installed as direct host functions (everything not via invoke). */
const directMethods = hostMethods.filter((m) => m.via !== "invoke");

const SWIFT_ARG: Record<ArgType, string> = {
  string: "String",
  int: "Int",
  double: "Double",
};
const SWIFT_RET: Record<ReturnType, string> = {
  void: "Void",
  "string?": "String?",
  int: "Int",
};
const TS_ARG: Record<ArgType, string> = {
  string: "string",
  int: "number",
  double: "number",
};
const TS_RET: Record<ReturnType, string> = {
  void: "void",
  "string?": "string | null",
  int: "number",
};

const argsOf = (m: HostMethod): HostArg[] => m.args ?? [];
const retOf = (m: HostMethod): ReturnType => m.returns ?? "void";
/** C trampoline name for a method, lowerCamelCase (swift-format requires it). */
const trampoline = (m: HostMethod) =>
  `host${m.name[0].toUpperCase()}${m.name.slice(1)}`;

/** Swift closure type for a method, e.g. `((String, Int) -> Int)`. */
function swiftClosureType(m: HostMethod) {
  const params = argsOf(m)
    .map((a) => SWIFT_ARG[a.type])
    .join(", ");
  return `((${params}) -> ${SWIFT_RET[retOf(m)]})`;
}

/** One generated C trampoline: recover the runtime, marshal args by type, call
 *  the bridge closure, marshal the return. @convention(c) can't capture, so the
 *  runtime is recovered from the context opaque pointer. */
function swiftTrampoline(m: HostMethod) {
  const args = argsOf(m);
  const ret = retOf(m);
  const fail =
    ret === "string?"
      ? "qjs_null()"
      : ret === "int"
        ? "JS_NewInt32(ctx, 0)"
        : "qjs_undefined()";
  // A zero-arg method reads neither argv nor argc, so binding them would only
  // produce an unused-value warning (and an always-true `argc >= 0`).
  const guard = [
    "let runtime = JSRuntime.from(context: ctx)",
    ...(args.length > 0 ? ["let argv", `argc >= ${args.length}`] : []),
    ...args
      .map((a, i) => [a, i] as const)
      .filter(([a]) => a.type === "string")
      .map(([, i]) => `let arg${i}Cstr = JS_ToCString(ctx, argv[${i}])`),
  ].join(", ");

  const body: string[] = [];
  for (const [a, i] of args.map((a, i) => [a, i] as const)) {
    if (a.type === "string")
      body.push(`let arg${i} = String(cString: arg${i}Cstr)`);
  }
  for (const [a, i] of args.map((a, i) => [a, i] as const)) {
    if (a.type === "string") body.push(`JS_FreeCString(ctx, arg${i}Cstr)`);
  }
  for (const [a, i] of args.map((a, i) => [a, i] as const)) {
    if (a.type === "int") {
      body.push(
        `var arg${i}: Int32 = 0`,
        `JS_ToInt32(ctx, &arg${i}, argv[${i}])`,
      );
    } else if (a.type === "double") {
      body.push(
        `var arg${i}: Double = 0`,
        `JS_ToFloat64(ctx, &arg${i}, argv[${i}])`,
      );
    }
  }
  const callArgs = args
    .map((a, i) => (a.type === "int" ? `Int(arg${i})` : `arg${i}`))
    .join(", ");
  const call = `runtime.bridge.${m.name}?(${callArgs})`;
  if (ret === "void") {
    body.push(call, "return qjs_undefined()");
  } else if (ret === "int") {
    body.push(
      `let result = ${call} ?? 0`,
      "return JS_NewInt32(ctx, Int32(result))",
    );
  } else {
    body.push(`guard let result = ${call} else { return qjs_null() }`);
    body.push("return JS_NewString(ctx, result)");
  }

  return [
    `private func ${trampoline(m)}(`,
    "    ctx: OpaquePointer?, thisVal _: JSValue, argc: Int32,",
    "    argv: UnsafeMutablePointer<JSValue>?",
    ") -> JSValue {",
    `    guard ${guard}`,
    `    else { return ${fail} }`,
    ...body.map((l) => `    ${l}`),
    "}",
  ].join("\n");
}

function hostBridgeSwift() {
  const fields = directMethods.map(
    (m) => `    public var ${m.name}: ${swiftClosureType(m)}?`,
  );
  const installLine = (m: HostMethod) =>
    `        JS_SetPropertyStr(\n            context, host, "${m.name}",\n            JS_NewCFunction(context, ${trampoline(m)}, "${m.name}", ${argsOf(m).length}))`;
  // One target group's install lines, grouped by feature in schema
  // (first-appearance) order — deterministic, and each feature's methods are
  // contiguous in the schema today, so the method order is unchanged. "core"
  // installs stay unconditional (a policy must not be able to brick
  // commit/log/timers/invoke); every other feature's block is wrapped in an
  // `allows(...)` guard (ARCH-07). Order across features doesn't matter
  // semantically: each line is an independent property-set on `host`.
  const guardedInstalls = (methods: HostMethod[]): string[] => {
    const groups = new Map<string, HostMethod[]>();
    for (const m of methods) {
      const group = groups.get(m.feature);
      if (group) group.push(m);
      else groups.set(m.feature, [m]);
    }
    const lines: string[] = [];
    for (const [feature, group] of groups) {
      if (feature === "core") {
        lines.push(...group.map(installLine));
      } else {
        lines.push(`        if allows("${feature}") {`);
        lines.push(...group.map((m) => `    ${installLine(m)}`));
        lines.push("        }");
      }
    }
    return lines;
  };
  // Group the installs by target: shared functions go on every embedding;
  // watch-only ones are omitted in the widget extension so JS feature detection
  // (typeof __host.fetch) is correct there and a stray call fails loudly instead
  // of hanging on a nil-backed no-op trampoline (the widget never sets those).
  const inTarget = (m: HostMethod, t: WireTarget) => m.targets.includes(t);
  const sharedInstalls = guardedInstalls(
    directMethods.filter((m) => inTarget(m, "watch") && inTarget(m, "widget")),
  );
  const watchOnlyInstalls = guardedInstalls(
    directMethods.filter((m) => inTarget(m, "watch") && !inTarget(m, "widget")),
  );
  const widgetOnlyInstalls = guardedInstalls(
    directMethods.filter((m) => !inTarget(m, "watch") && inTarget(m, "widget")),
  );
  const targetedBlock = (installs: string[], target: string) =>
    installs.length === 0
      ? []
      : [
          `        if target == .${target} {`,
          ...installs.map((l) => `    ${l}`),
          "        }",
        ];
  return `${[
    banner(),
    "import CQuickJS",
    "",
    "/// Which embedding is installing the bridge — selects which host functions",
    "/// are exposed on `__host`. Generated from each method's schema `targets`.",
    "public enum HostTarget: Sendable {",
    "    case watch",
    "    case widget",
    "}",
    "",
    "/// Every synchronous `__host` callback the JS bridge dispatches to. The",
    "/// embedding host (ReactWatchHost / IntentRuntime) sets the feature closures;",
    "/// JSRuntime sets the infra ones (setTimer/clearTimer/log) to internal",
    '/// defaults. `via: "invoke"` methods are NOT here — they go through the',
    "/// generic invoke channel.",
    "public struct HostBridge {",
    ...fields,
    "",
    "    public init() {}",
    "}",
    "",
    "extension JSRuntime {",
    "    /// Installs the generated host functions onto `__host` for `target`.",
    "    /// Watch-only functions are absent in the widget so JS feature detection",
    "    /// is correct there and a stray call fails loudly, not silently hangs.",
    "    /// `allowedFeatures` is the HostPolicy ceiling (ARCH-07): nil installs",
    '    /// everything the target backs; otherwise only allowed features\' methods',
    '    /// are installed — except "core" (commit/log/timers/invoke), which is',
    "    /// always installed because the runtime can't operate without it.",
    "    func installHostBridge(",
    "        into host: JSValue, context: OpaquePointer, target: HostTarget,",
    "        allowedFeatures: Set<String>?",
    "    ) {",
    "        func allows(_ feature: String) -> Bool {",
    "            allowedFeatures?.contains(feature) ?? true",
    "        }",
    ...sharedInstalls,
    ...targetedBlock(watchOnlyInstalls, "watch"),
    ...targetedBlock(widgetOnlyInstalls, "widget"),
    "    }",
    "}",
    "",
    "// @convention(c) trampolines: no captures, so each recovers its JSRuntime",
    "// from the context opaque pointer, marshals the args, and dispatches.",
    "",
    ...directMethods.map(swiftTrampoline).flatMap((t) => [t, ""]),
  ]
    .join("\n")
    .trimEnd()}\n`;
}

/** The TS `QuickJSHostGlobal` interface — the raw string/number bridge JS sees. */
function quickJSHostGlobalTS() {
  const lines = [
    "/** Raw globals installed by the host before the bundle is evaluated",
    " *  (generated from the schema's direct methods). Strings/numbers cross the C",
    ' *  boundary; commit/event payloads are JSON strings. `via:"invoke"` methods',
    " *  are routed through `invoke`, not installed here. */",
    "export interface QuickJSHostGlobal {",
  ];
  for (const m of directMethods) {
    if (m.doc) lines.push(`  /** ${m.doc} */`);
    const params = argsOf(m)
      .map((a) => `${a.name}: ${TS_ARG[a.type]}`)
      .join(", ");
    const opt = m.tsRequired ? "" : "?";
    lines.push(`  ${m.name}${opt}(${params}): ${TS_RET[retOf(m)]};`);
  }
  lines.push("}");
  return lines.join("\n");
}

// --- Swift -----------------------------------------------------------------

const JSON_VALUE_SWIFT = `public enum JSONValue: Codable, Equatable, Sendable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case array([JSONValue])
    case object([String: JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let bool = try? container.decode(Bool.self) {
            self = .bool(bool)
        } else if let number = try? container.decode(Double.self) {
            self = .number(number)
        } else if let string = try? container.decode(String.self) {
            self = .string(string)
        } else if let array = try? container.decode([JSONValue].self) {
            self = .array(array)
        } else if let object = try? container.decode([String: JSONValue].self) {
            self = .object(object)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container, debugDescription: "Unsupported JSON value")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}`;

const nodeSwift =
  () => `public struct ${node.swift}: Codable, Equatable, Identifiable, Sendable {
    public let id: Int
    public let type: String
    public let props: [String: JSONValue]
    public let children: [${node.swift}]

    public func string(_ key: String) -> String? {
        if case .string(let value)? = props[key] { return value }
        return nil
    }

    public func double(_ key: String) -> Double? {
        if case .number(let value)? = props[key] { return value }
        return nil
    }

    public func bool(_ key: String) -> Bool? {
        if case .bool(let value)? = props[key] { return value }
        return nil
    }

    public func stringArray(_ key: String) -> [String]? {
        guard case .array(let values)? = props[key] else { return nil }
        return values.compactMap {
            if case .string(let value) = $0 { return value }
            return nil
        }
    }
}`;

function swiftStruct(def: StructDef) {
  const lines = [`public struct ${def.swift}: Codable, Equatable, Sendable {`];
  for (const f of def.fields) {
    if (f.doc) lines.push(`    /// ${f.doc}`);
    lines.push(`    public let ${f.name}: ${f.swift}`);
  }
  for (const computed of def.swiftComputed ?? []) {
    lines.push("");
    lines.push(`    public ${computed}`);
  }
  lines.push("}");
  return lines.join("\n");
}

// One unified module (ReactWatchCore) for both the watch host and the widget,
// so JSONValue + RNNode are defined once. All `public` for cross-module use.
function swiftModel() {
  const parts = [
    banner(),
    "import Foundation",
    "",
    JSON_VALUE_SWIFT,
    "",
    nodeSwift(),
  ];
  for (const def of structs) parts.push("", swiftStruct(def));
  // Expose the committed-tree wire version so the runtime can flag a
  // renderer-vs-runtime mismatch (see ReactAppModel.decode).
  parts.push(
    "",
    "public enum RNWire {",
    `    public static let version = ${wireVersion}`,
    `    public static let bridgeProtocol = ${bridgeProtocol}`,
    "}",
  );
  const swiftSet = (target: WireTarget) =>
    `[${featuresFor(target)
      .map((f) => `"${f}"`)
      .join(", ")}]`;
  parts.push(
    "",
    "/// The capability features each native target provides (ARCH-01). A bundle",
    "/// runs only if its required features are a subset (see CapabilityGate).",
    "public enum HostFeatures {",
    `    public static let watch: Set<String> = ${swiftSet("watch")}`,
    `    public static let widget: Set<String> = ${swiftSet("widget")}`,
    "}",
  );
  // via:"invoke" methods aren't installed as host functions, so the ARCH-07
  // install guards can't gate them — the invoke dispatcher checks this map
  // before routing instead.
  const invokeMethods = hostMethods
    .filter((m) => m.via === "invoke")
    .sort((a, b) => (a.name < b.name ? -1 : 1));
  parts.push(
    "",
    "/// Feature id for each invoke-routed host method (ARCH-07). The host checks",
    "/// it BEFORE dispatching an invoke, so a feature the consumer's HostPolicy",
    "/// didn't authorize rejects typed (POLICY_DENIED) instead of reaching a",
    "/// handler.",
    "public enum HostInvokeFeatures {",
    "    public static let byMethod: [String: String] = [",
    ...invokeMethods.map((m) => `        "${m.name}": "${m.feature}",`),
    "    ]",
    "}",
  );
  return `${parts.join("\n")}\n`;
}

// --- Invoke channel shapes (ARCH-11) ---------------------------------------
// The `via:"invoke"` methods' request/result shapes are a CONTRACT, not a
// runtime dependency: TS interfaces land in the wire module (so a caller and a
// fixture can be typed by them), and the Swift side is emitted into the TEST
// target only. The 31 handlers keep their own decoders — see the doc on
// `invokeShapes` for why the generated-Codable-handler variant was rejected —
// so emitting these structs into ReactWatchCore would put ~20 types nobody
// instantiates into both shipping binaries, including the widget extension.

const invokeMethods = hostMethods.filter((m) => m.via === "invoke");
const shapeByTs = new Map(invokeShapes.map((s) => [s.ts, s]));

/** Splits a `HostMethod.request`/`.response` ref into its shape + arrayness.
 *  `"opaque"` returns null — the payload is the app's own JSON by contract. */
function resolveShape(
  ref: string | undefined,
): { def: StructDef; array: boolean } | null {
  if (!ref || ref === "opaque") return null;
  const array = ref.endsWith("[]");
  const name = array ? ref.slice(0, -2) : ref;
  const def = shapeByTs.get(name);
  if (!def) throw new Error(`unknown invoke shape "${name}"`);
  return { def, array };
}

/** `{ method: { request?, response? } }` — the shape refs as DATA, so the JS
 *  contract test can assert it covers every payload-carrying method without
 *  re-listing them. `"opaque"` is carried through verbatim. */
function invokeShapesTS() {
  const table: Record<string, { request?: string; response?: string }> = {};
  for (const m of invokeMethods) {
    if (!m.request && !m.response) continue;
    table[m.name] = {
      ...(m.request ? { request: m.request } : {}),
      ...(m.response ? { response: m.response } : {}),
    };
  }
  return [
    "/** ARCH-11: the declared request/result shape of each `via:\"invoke\"`",
    " *  method that carries one. A value of `\"opaque\"` means the payload is the",
    " *  consuming app's own JSON by contract (the connectivity channels), not an",
    " *  undeclared shape. Methods absent from this table send no payload and",
    " *  return void/null, a bare string, `string[]`, or a boolean. */",
    `export const INVOKE_SHAPES = ${JSON.stringify(table)} as const;`,
  ].join("\n");
}

/** The Swift half — Codable mirrors of `invokeShapes` plus per-method decode
 *  tables, emitted into the test target. Internal (not `public`): nothing
 *  outside `swift test` may depend on these. */
function invokeShapesSwift() {
  const struct = (def: StructDef) => {
    const lines = [];
    if (def.doc) lines.push(`/// ${def.doc}`);
    lines.push(`struct ${def.swift}: InvokeShape {`);
    for (const f of def.fields) {
      if (f.doc) lines.push(`    /// ${f.doc}`);
      lines.push(`    let ${f.name}: ${f.swift}`);
    }
    lines.push(
      `    static let declaredKeys: Set<String> = [${def.fields
        .map((f) => `"${f.name}"`)
        .join(", ")}]`,
    );
    lines.push("}");
    return lines.join("\n");
  };
  const entry = (m: HostMethod, ref: string | undefined) => {
    const shape = resolveShape(ref);
    if (!shape) return null;
    const call = shape.array
      ? `try decodeStrict(arrayOf: ${shape.def.swift}.self, from: $0)`
      : `try decodeStrict(${shape.def.swift}.self, from: $0)`;
    return `        "${m.name}": { ${call} },`;
  };
  const requests = invokeMethods
    .map((m) => entry(m, m.request))
    .filter((line) => line !== null);
  const responses = invokeMethods
    .map((m) => entry(m, m.response))
    .filter((line) => line !== null);
  const opaque = invokeMethods
    .filter((m) => m.request === "opaque")
    .map((m) => `"${m.name}"`);
  return `${[
    banner(),
    "import Foundation",
    "import ReactWatchCore",
    "",
    "// The SD-1 invoke channel's schema-declared shapes (ARCH-11), rendered for",
    "// the TEST target only: InvokeContractTests decodes the JS-produced",
    "// Fixtures/invoke-*.json with these, so a wrapper that changes its payload",
    "// (or a native result that changes its keys) fails `swift test` instead of",
    "// on a watch. The 31 handlers keep their own decoders by design.",
    "//",
    "// The decode is STRICT about undeclared keys, because a synthesized",
    "// `Codable` init ignores unknown keys AND maps a missing key for an",
    "// Optional property to nil — so a plain decode is blind to every rename or",
    "// addition of an OPTIONAL field (the majority of the declared surface), and",
    "// the JS suite would just rewrite the fixture around the drift. A rename",
    "// always shows up as (tolerated missing key) + (extra unknown key), so",
    "// rejecting unknown keys catches renames and additions with one check.",
    "",
    "protocol InvokeShape: Codable, Equatable {",
    "    /// Every key the schema declares for this shape.",
    "    static var declaredKeys: Set<String> { get }",
    "}",
    "",
    "struct UndeclaredInvokeKeys: Error, CustomStringConvertible {",
    "    let shape: String",
    "    let keys: [String]",
    "    var description: String {",
    '        "\\(shape) has undeclared payload keys \\(keys.sorted()) — the schema "',
    '            + "does not declare them, so no handler reads them"',
    "    }",
    "}",
    "",
    "private func assertDeclared<T: InvokeShape>(",
    "    _: T.Type, _ object: [String: JSONValue]",
    ") throws {",
    "    let extra = Set(object.keys).subtracting(T.declaredKeys)",
    "    guard extra.isEmpty else {",
    '        throw UndeclaredInvokeKeys(shape: "\\(T.self)", keys: Array(extra))',
    "    }",
    "}",
    "",
    "func decodeStrict<T: InvokeShape>(_ type: T.Type, from data: Data) throws {",
    "    _ = try JSONDecoder().decode(T.self, from: data)",
    "    try assertDeclared(",
    "        type, try JSONDecoder().decode([String: JSONValue].self, from: data))",
    "}",
    "",
    "func decodeStrict<T: InvokeShape>(arrayOf type: T.Type, from data: Data) throws {",
    "    _ = try JSONDecoder().decode([T].self, from: data)",
    "    for object in try JSONDecoder().decode(",
    "        [[String: JSONValue]].self, from: data)",
    "    {",
    "        try assertDeclared(type, object)",
    "    }",
    "}",
    "",
    ...invokeShapes.map(struct).flatMap((s) => [s, ""]),
    "enum InvokeShapes {",
    "    /// method -> decode this fixture as the declared REQUEST shape.",
    "    static let requestDecoders: [String: @Sendable (Data) throws -> Void] = [",
    ...requests,
    "    ]",
    "",
    "    /// method -> decode this fixture as the declared RESULT shape.",
    "    static let responseDecoders: [String: @Sendable (Data) throws -> Void] = [",
    ...responses,
    "    ]",
    "",
    "    /// Payloads that are the consuming app's own JSON by contract — Swift",
    "    /// hands them to WCSession as [String: Any] without reading a field, so",
    "    /// no schema can (or should) describe them.",
    `    static let opaqueRequests: Set<String> = [${opaque.join(", ")}]`,
    "}",
  ]
    .join("\n")
    .trimEnd()}\n`;
}

// --- TypeScript ------------------------------------------------------------

function tsInterface(def: StructDef | TsOnlyDef) {
  const lines: string[] = [];
  if (def.doc) lines.push(`/** ${def.doc} */`);
  lines.push(`export interface ${def.ts} {`);
  for (const f of def.fields) {
    const opt = f.optional ? "?" : "";
    const doc = f.doc ? ` // ${f.doc}` : "";
    lines.push(`  ${f.name}${opt}: ${f.ts};${doc}`);
  }
  lines.push("}");
  return lines.join("\n");
}

/** A closed string union rendered one member per line — the vocabularies
 *  (health types, workout activity types) that Swift must switch over too. */
function tsUnion(name: string, members: string[], doc: string) {
  return [
    `/** ${doc} */`,
    `export type ${name} =`,
    ...members.map((m) => `  | "${m}"`),
    "  ;",
  ].join("\n");
}

function tsModel() {
  const parts = [
    banner(),
    "/* eslint-disable */",
    "export type JSONValue =",
    "  | string | number | boolean | JSONValue[]",
    "  | { [key: string]: JSONValue } | null;",
    "",
    `export interface ${node.ts} {`,
    "  id: number;",
    "  type: string;",
    "  props: Record<string, unknown>;",
    `  children: ${node.ts}[];`,
    "}",
    "",
    tsUnion(
      "HealthQuantityType",
      healthQuantityTypes,
      "The HealthKit quantity types this bridge reads. Closed: an unbound " +
        "type would type-check and resolve null forever.",
    ),
    "",
    tsUnion(
      "WorkoutActivityType",
      workoutActivityTypes,
      "Every live HKWorkoutActivityType member (the 3 deprecated spellings " +
        "excluded). Swift maps the NAME to the case; raw values are " +
        "undocumented.",
    ),
  ];
  for (const def of [...structs, ...tsOnly, ...invokeShapes])
    parts.push("", tsInterface(def));
  const manifest = JSON.stringify(
    hostMethods.map((m) => ({
      name: m.name,
      targets: m.targets,
      feature: m.feature,
      since: m.since,
      ...(m.via ? { via: m.via } : {}),
    })),
  );
  parts.push(
    "",
    "/** Native bridge methods: which runtime installs each, the capability",
    " *  `feature` an OTA bundle gates on, and the bridgeProtocol it shipped in. */",
    `export const HOST_METHODS = ${manifest} as const;`,
    "",
    "/** Committed-tree wire version (SerializedTree.v). Bump on shape changes. */",
    `export const WIRE_VERSION = ${wireVersion} as const;`,
    "",
    "/** JS<->Swift host bridge protocol version (ARCH-01). */",
    `export const BRIDGE_PROTOCOL = ${bridgeProtocol} as const;`,
    "",
    "/** Capability features each native target provides (ARCH-01). */",
    `export const HOST_FEATURES = ${JSON.stringify({
      watch: featuresFor("watch"),
      widget: featuresFor("widget"),
    })} as const;`,
    "",
    "/** The component contract (CX-024): every primitive the tree can emit and",
    " *  how the widget interpreter supports it (full | degraded). Both Swift",
    " *  interpreters are drift-tested against this. */",
    `export const COMPONENTS = ${JSON.stringify(components)} as const;`,
    "",
    invokeShapesTS(),
    "",
    quickJSHostGlobalTS(),
  );
  return `${parts.join("\n")}\n`;
}

// --- Workout activity names (watchOS host) ---------------------------------
// The other half of the `workoutActivityTypes` vocabulary: JS sends the case
// NAME and Swift needs an HKWorkoutActivityType. `HKWorkoutActivityType` is an
// ObjC NS_ENUM with UInt raw values that Apple does NOT document, so a numeric
// round trip could silently land on a different activity — the mapping has to
// be a name switch, and generating it from the same list the TS union comes
// from is what makes name-vs-case drift impossible. Lives in ReactWatchHost
// (it imports HealthKit) and compiles out off-watchOS like the rest of it.

function workoutActivityNameSwift() {
  return `${[
    banner(),
    "#if os(watchOS)",
    "import HealthKit",
    "",
    "/// Maps a wire `WorkoutActivityType` name to its HKWorkoutActivityType",
    "/// case. `nil` = a name this binary doesn't know, which the workout",
    "/// handler rejects INVALID_REQUEST rather than silently starting `.other`.",
    "enum WorkoutActivityName {",
    "    static func type(for name: String) -> HKWorkoutActivityType? {",
    "        switch name {",
    ...workoutActivityTypes.map((n) => `        case "${n}": .${n}`),
    "        default: nil",
    "        }",
    "    }",
    "",
    "    /// The same table read backwards, for the one session this process does",
    "    /// NOT construct from a wire payload: a workout recovered from a launch",
    "    /// that crashed. HealthKit hands back the session and its",
    "    /// `HKWorkoutConfiguration`, so the activity arrives as a case and has to",
    "    /// be named before `getWorkoutState()` can report it. `nil` = a case this",
    "    /// vocabulary excludes (the three deprecated spellings), and the snapshot",
    "    /// then OMITS `activityType` rather than naming the wrong workout.",
    "    static func name(for type: HKWorkoutActivityType) -> String? {",
    "        switch type {",
    ...workoutActivityTypes.map((n) => `        case .${n}: "${n}"`),
    "        default: nil",
    "        }",
    "    }",
    "}",
    "#endif",
  ]
    .join("\n")
    .trimEnd()}\n`;
}

// --- Outputs ---------------------------------------------------------------

const outputs = [
  ["swift/Sources/ReactWatchCore/WireModel.swift", swiftModel()],
  [
    "swift/Sources/ReactWatchRuntime/Generated/HostBridge.swift",
    hostBridgeSwift(),
  ],
  [
    "swift/Sources/ReactWatchHost/Generated/WorkoutActivityName.swift",
    workoutActivityNameSwift(),
  ],
  [
    "swift/Tests/ReactWatchTests/Generated/InvokeShapes.swift",
    invokeShapesSwift(),
  ],
  ["src/generated/wire.ts", tsModel()],
];

const check = process.argv.includes("--check");
let stale = 0;
for (const [rel, content] of outputs) {
  const path = join(root, rel);
  // Swift output is formatter-owned (swift-format); TS output keeps its emitted
  // shape (biome-ignored). Both stay drift-checked.
  const final = rel.endsWith(".swift") ? formatSwift(content) : content;
  if (check) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      /* missing */
    }
    if (current !== final) {
      console.error(`stale: ${rel}`);
      stale += 1;
    }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, final);
    console.log(`wrote ${rel}`);
  }
}
if (check && stale > 0) {
  console.error(
    `\n${stale} generated file(s) out of date — run \`npm run codegen\`.`,
  );
  process.exit(1);
}
