// Renders codegen/schema.mjs into Swift models (watch + widget) and TS wire
// types. Run `npm run codegen` after editing the schema. `--check` exits
// non-zero if the committed output is stale (used by the drift test).

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  bridgeProtocol,
  components,
  hostMethods,
  node,
  structs,
  tsOnly,
  wireVersion,
} from "./schema.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// Generated Swift is piped through Apple's swift-format with the repo's
// `.swift-format` config, so the output is formatter-clean and never needs
// excluding from a `swift format` run (the generated TS is biome-ignored
// separately). Needs the toolchain's `swift format` (bundled with Xcode 16+ /
// Swift 6) — the same tool that formats the hand-written sources.
const swiftFormatConfig = join(root, "..", ".swift-format");
function formatSwift(source) {
  try {
    // `-` reads the source from stdin (implicit stdin is deprecated).
    return execFileSync(
      "swift",
      ["format", "--configuration", swiftFormatConfig, "-"],
      { input: source, encoding: "utf8" },
    );
  } catch (error) {
    throw new Error(
      "swift-format failed to format generated Swift — is the Swift toolchain " +
        `installed? \`swift format\` is required by codegen.\n${error.message}`,
    );
  }
}
const banner = () =>
  `// @generated by js/codegen/generate.mjs — DO NOT EDIT.\n// Run \`npm run codegen\` after editing js/codegen/schema.mjs.\n`;

/** The unique capability features a native `target` provides (ARCH-01),
 *  derived from the host methods it installs. */
const featuresFor = (target) =>
  [
    ...new Set(
      hostMethods
        .filter((m) => m.targets.includes(target))
        .map((m) => m.feature),
    ),
  ].sort();

// --- Host bridge (CX-023) --------------------------------------------------
// The synchronous `__host` surface is generated end-to-end from the method
// signatures: the TS `QuickJSHostGlobal`, the Swift `HostBridge` callbacks, the
// C trampolines, and the install table. `via: "invoke"` methods are routed
// through the generic channel, so they're not part of this surface.

/** Methods installed as direct host functions (everything not via invoke). */
const directMethods = hostMethods.filter((m) => m.via !== "invoke");

const SWIFT_ARG = { string: "String", int: "Int", double: "Double" };
const SWIFT_RET = { void: "Void", "string?": "String?", int: "Int" };
const TS_ARG = { string: "string", int: "number", double: "number" };
const TS_RET = { void: "void", "string?": "string | null", int: "number" };

const argsOf = (m) => m.args ?? [];
const retOf = (m) => m.returns ?? "void";
/** C trampoline name for a method, lowerCamelCase (swift-format requires it). */
const trampoline = (m) => `host${m.name[0].toUpperCase()}${m.name.slice(1)}`;

/** Swift closure type for a method, e.g. `((String, Int) -> Int)`. */
function swiftClosureType(m) {
  const params = argsOf(m)
    .map((a) => SWIFT_ARG[a.type])
    .join(", ");
  return `((${params}) -> ${SWIFT_RET[retOf(m)]})`;
}

/** One generated C trampoline: recover the runtime, marshal args by type, call
 *  the bridge closure, marshal the return. @convention(c) can't capture, so the
 *  runtime is recovered from the context opaque pointer. */
function swiftTrampoline(m) {
  const args = argsOf(m);
  const ret = retOf(m);
  const fail =
    ret === "string?"
      ? "qjs_null()"
      : ret === "int"
        ? "JS_NewInt32(ctx, 0)"
        : "qjs_undefined()";
  const guard = [
    "let runtime = JSRuntime.from(context: ctx)",
    "let argv",
    `argc >= ${args.length}`,
    ...args
      .map((a, i) => [a, i])
      .filter(([a]) => a.type === "string")
      .map(([, i]) => `let arg${i}Cstr = JS_ToCString(ctx, argv[${i}])`),
  ].join(", ");

  const body = [];
  for (const [a, i] of args.map((a, i) => [a, i])) {
    if (a.type === "string")
      body.push(`let arg${i} = String(cString: arg${i}Cstr)`);
  }
  for (const [a, i] of args.map((a, i) => [a, i])) {
    if (a.type === "string") body.push(`JS_FreeCString(ctx, arg${i}Cstr)`);
  }
  for (const [a, i] of args.map((a, i) => [a, i])) {
    if (a.type === "int") {
      body.push(
        `var arg${i}: Int32 = 0`,
        `JS_ToInt32(ctx, &arg${i}, argv[${i}])`,
      );
    } else if (a.type === "double") {
      body.push(
        `var arg${i}: Double = 0`,
        `JS_ToFloat64(ctx, &arg${i}, argv[${i}])`,
      );
    }
  }
  const callArgs = args
    .map((a, i) => (a.type === "int" ? `Int(arg${i})` : `arg${i}`))
    .join(", ");
  const call = `runtime.bridge.${m.name}?(${callArgs})`;
  if (ret === "void") {
    body.push(call, "return qjs_undefined()");
  } else if (ret === "int") {
    body.push(
      `let result = ${call} ?? 0`,
      "return JS_NewInt32(ctx, Int32(result))",
    );
  } else {
    body.push(`guard let result = ${call} else { return qjs_null() }`);
    body.push("return JS_NewString(ctx, result)");
  }

  return [
    `private func ${trampoline(m)}(`,
    "    ctx: OpaquePointer?, thisVal _: JSValue, argc: Int32,",
    "    argv: UnsafeMutablePointer<JSValue>?",
    ") -> JSValue {",
    `    guard ${guard}`,
    `    else { return ${fail} }`,
    ...body.map((l) => `    ${l}`),
    "}",
  ].join("\n");
}

function hostBridgeSwift() {
  const fields = directMethods.map(
    (m) => `    public var ${m.name}: ${swiftClosureType(m)}?`,
  );
  const installs = directMethods.map(
    (m) =>
      `        JS_SetPropertyStr(\n            context, host, "${m.name}",\n            JS_NewCFunction(context, ${trampoline(m)}, "${m.name}", ${argsOf(m).length}))`,
  );
  return `${[
    banner(),
    "import CQuickJS",
    "",
    "/// Every synchronous `__host` callback the JS bridge dispatches to. The",
    "/// embedding host (ReactWatchHost / IntentRuntime) sets the feature closures;",
    "/// JSRuntime sets the infra ones (setTimer/clearTimer/log) to internal",
    '/// defaults. `via: "invoke"` methods are NOT here — they go through the',
    "/// generic invoke channel.",
    "public struct HostBridge {",
    ...fields,
    "",
    "    public init() {}",
    "}",
    "",
    "extension JSRuntime {",
    "    /// Installs every generated host function onto the `__host` object.",
    "    func installHostBridge(into host: JSValue, context: OpaquePointer) {",
    ...installs,
    "    }",
    "}",
    "",
    "// @convention(c) trampolines: no captures, so each recovers its JSRuntime",
    "// from the context opaque pointer, marshals the args, and dispatches.",
    "",
    ...directMethods.map(swiftTrampoline).flatMap((t) => [t, ""]),
  ]
    .join("\n")
    .trimEnd()}\n`;
}

/** The TS `QuickJSHostGlobal` interface — the raw string/number bridge JS sees. */
function quickJSHostGlobalTS() {
  const lines = [
    "/** Raw globals installed by the host before the bundle is evaluated",
    " *  (generated from the schema's direct methods). Strings/numbers cross the C",
    ' *  boundary; commit/event payloads are JSON strings. `via:"invoke"` methods',
    " *  are routed through `invoke`, not installed here. */",
    "export interface QuickJSHostGlobal {",
  ];
  for (const m of directMethods) {
    if (m.doc) lines.push(`  /** ${m.doc} */`);
    const params = argsOf(m)
      .map((a) => `${a.name}: ${TS_ARG[a.type]}`)
      .join(", ");
    const opt = m.tsRequired ? "" : "?";
    lines.push(`  ${m.name}${opt}(${params}): ${TS_RET[retOf(m)]};`);
  }
  lines.push("}");
  return lines.join("\n");
}

// --- Swift -----------------------------------------------------------------

const JSON_VALUE_SWIFT = `public enum JSONValue: Codable, Equatable, Sendable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case array([JSONValue])
    case object([String: JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let bool = try? container.decode(Bool.self) {
            self = .bool(bool)
        } else if let number = try? container.decode(Double.self) {
            self = .number(number)
        } else if let string = try? container.decode(String.self) {
            self = .string(string)
        } else if let array = try? container.decode([JSONValue].self) {
            self = .array(array)
        } else if let object = try? container.decode([String: JSONValue].self) {
            self = .object(object)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container, debugDescription: "Unsupported JSON value")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}`;

const nodeSwift =
  () => `public struct ${node.swift}: Codable, Equatable, Identifiable, Sendable {
    public let id: Int
    public let type: String
    public let props: [String: JSONValue]
    public let children: [${node.swift}]

    public func string(_ key: String) -> String? {
        if case .string(let value)? = props[key] { return value }
        return nil
    }

    public func double(_ key: String) -> Double? {
        if case .number(let value)? = props[key] { return value }
        return nil
    }

    public func bool(_ key: String) -> Bool? {
        if case .bool(let value)? = props[key] { return value }
        return nil
    }

    public func stringArray(_ key: String) -> [String]? {
        guard case .array(let values)? = props[key] else { return nil }
        return values.compactMap {
            if case .string(let value) = $0 { return value }
            return nil
        }
    }
}`;

function swiftStruct(def) {
  const lines = [`public struct ${def.swift}: Codable, Equatable, Sendable {`];
  for (const f of def.fields) {
    if (f.doc) lines.push(`    /// ${f.doc}`);
    lines.push(`    public let ${f.name}: ${f.swift}`);
  }
  for (const computed of def.swiftComputed ?? []) {
    lines.push("");
    lines.push(`    public ${computed}`);
  }
  lines.push("}");
  return lines.join("\n");
}

// One unified module (ReactWatchCore) for both the watch host and the widget,
// so JSONValue + RNNode are defined once. All `public` for cross-module use.
function swiftModel() {
  const parts = [
    banner(),
    "import Foundation",
    "",
    JSON_VALUE_SWIFT,
    "",
    nodeSwift(),
  ];
  for (const def of structs) parts.push("", swiftStruct(def));
  // Expose the committed-tree wire version so the runtime can flag a
  // renderer-vs-runtime mismatch (see ReactAppModel.decode).
  parts.push(
    "",
    "public enum RNWire {",
    `    public static let version = ${wireVersion}`,
    `    public static let bridgeProtocol = ${bridgeProtocol}`,
    "}",
  );
  const swiftSet = (target) =>
    `[${featuresFor(target)
      .map((f) => `"${f}"`)
      .join(", ")}]`;
  parts.push(
    "",
    "/// The capability features each native target provides (ARCH-01). A bundle",
    "/// runs only if its required features are a subset (see CapabilityGate).",
    "public enum HostFeatures {",
    `    public static let watch: Set<String> = ${swiftSet("watch")}`,
    `    public static let widget: Set<String> = ${swiftSet("widget")}`,
    "}",
  );
  return `${parts.join("\n")}\n`;
}

// --- TypeScript ------------------------------------------------------------

function tsInterface(def) {
  const lines = [];
  if (def.doc) lines.push(`/** ${def.doc} */`);
  lines.push(`export interface ${def.ts} {`);
  for (const f of def.fields) {
    const opt = f.optional ? "?" : "";
    const doc = f.doc ? ` // ${f.doc}` : "";
    lines.push(`  ${f.name}${opt}: ${f.ts};${doc}`);
  }
  lines.push("}");
  return lines.join("\n");
}

function tsModel() {
  const parts = [
    banner(),
    "/* eslint-disable */",
    "export type JSONValue =",
    "  | string | number | boolean | JSONValue[]",
    "  | { [key: string]: JSONValue } | null;",
    "",
    `export interface ${node.ts} {`,
    "  id: number;",
    "  type: string;",
    "  props: Record<string, unknown>;",
    `  children: ${node.ts}[];`,
    "}",
  ];
  for (const def of [...structs, ...tsOnly]) parts.push("", tsInterface(def));
  const manifest = JSON.stringify(
    hostMethods.map((m) => ({
      name: m.name,
      targets: m.targets,
      feature: m.feature,
      since: m.since,
      ...(m.via ? { via: m.via } : {}),
    })),
  );
  parts.push(
    "",
    "/** Native bridge methods: which runtime installs each, the capability",
    " *  `feature` an OTA bundle gates on, and the bridgeProtocol it shipped in. */",
    `export const HOST_METHODS = ${manifest} as const;`,
    "",
    "/** Committed-tree wire version (SerializedTree.v). Bump on shape changes. */",
    `export const WIRE_VERSION = ${wireVersion} as const;`,
    "",
    "/** JS<->Swift host bridge protocol version (ARCH-01). */",
    `export const BRIDGE_PROTOCOL = ${bridgeProtocol} as const;`,
    "",
    "/** Capability features each native target provides (ARCH-01). */",
    `export const HOST_FEATURES = ${JSON.stringify({
      watch: featuresFor("watch"),
      widget: featuresFor("widget"),
    })} as const;`,
    "",
    "/** The component contract (CX-024): every primitive the tree can emit and",
    " *  how the widget interpreter supports it (full | degraded). Both Swift",
    " *  interpreters are drift-tested against this. */",
    `export const COMPONENTS = ${JSON.stringify(components)} as const;`,
    "",
    quickJSHostGlobalTS(),
  );
  return `${parts.join("\n")}\n`;
}

// --- Outputs ---------------------------------------------------------------

const outputs = [
  ["swift/Sources/ReactWatchCore/WireModel.swift", swiftModel()],
  [
    "swift/Sources/ReactWatchRuntime/Generated/HostBridge.swift",
    hostBridgeSwift(),
  ],
  ["src/generated/wire.ts", tsModel()],
];

const check = process.argv.includes("--check");
let stale = 0;
for (const [rel, content] of outputs) {
  const path = join(root, rel);
  // Swift output is formatter-owned (swift-format); TS output keeps its emitted
  // shape (biome-ignored). Both stay drift-checked.
  const final = rel.endsWith(".swift") ? formatSwift(content) : content;
  if (check) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      /* missing */
    }
    if (current !== final) {
      console.error(`stale: ${rel}`);
      stale += 1;
    }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, final);
    console.log(`wrote ${rel}`);
  }
}
if (check && stale > 0) {
  console.error(
    `\n${stale} generated file(s) out of date — run \`npm run codegen\`.`,
  );
  process.exit(1);
}
